spring:
  datasource:
#    url: jdbc:postgresql://db:5432/glossy-db
    url: jdbc:postgresql://localhost:5432/ricardoyalico
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080
